###################################
#			SET SERVICES		  #
###################################

version: '3'

services:
    jenkins:
        build: .

#######################################
#			SET PORT LOCALHOST		  #
#######################################

        ports:
            - "8080:8080"

###################################
#			ADD FILE .ENV		  #
###################################

        env_file:
            - .env

#######################################
#			SET VOLUME JENKINS		  #
#######################################

        volumes:
            - jenkins_local:/var/jenkins_local
volumes:
    jenkins_local: