jenkins:
    systemMessage: "Automating Jenkins Setup using Docker and Jenkins Configuration as Code\n\n"
    remotingSecurity:
        enabled: true
    securityRealm:
        local:
          allowsSignup: true
          users:
              - id: ${USERNAME}
                password: ${PASSWORD}
    authorizationStrategy:
        globalMatrix:
            permissions:
                - "Overall/Administer:${USERNAME}"
                - "Overall/Read:authenticated"
unclassified:
  location:
    url: http://127.0.0.1:8080/

jobs:
    - file: /usr/local/job_dsl.groovy